FROM debian:bookworm

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
        firefox-esr \
        libgtk-3-0 \
        libdbus-glib-1-2 \
        libx11-xcb1 \
        libasound2 \
        x11-utils && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["firefox-esr"]

