#!/bin/bash

# Obtener el directorio actual
pwd=$(pwd)

# Obtener el nombre del directorio actual
foldername=$(basename "$pwd")

# Agregar la extensión .md al nombre del directorio
foldername_with_extension="$foldername.md"

# Ejecutar el script para obtener la dirección IP
resultado=$("$HOME/.config/bin/bateria.sh")

# Obtener la dirección IP del resultado
ip=$(echo "$resultado" | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b")

# Mostrar información y variables
echo "Definiendo las siguientes variables:"
echo ""
echo "export htf=\"$pwd/$foldername_with_extension\""
echo "export htcon=\"$pwd\""
echo "export ip=\"$ip\""

# Eliminar las líneas existentes del archivo .zshrc si ya están definidas
sed -i '/export htf=/d' ~/.zshrc
sed -i '/export htcon=/d' ~/.zshrc
sed -i '/export ip=/d' ~/.zshrc

# Añadir las líneas al final del archivo .zshrc
{
  echo ""
  echo "# Variables definidas por el script htp"
  echo "export htf=\"$pwd/$foldername_with_extension\""
  echo "export htcon=\"$pwd\""
  echo "export ip=\"$ip\""
} >> ~/.zshrc

# Notificar al usuario
echo ""
echo "Las variables han sido definidas y agregadas al archivo ~/.zshrc"
