#!/run/current-system/sw/bin/bash


sudo ls /opt/4rji/bin2 | xargs -n1 | sudo tee lista > /dev/null  


# Directorio base para eliminar archivos
base_dir="/opt/4rji/bin"

# Ruta del archivo lista
lista_file="/opt/4rji/bin2/lista"

# Lee el archivo lista línea por línea
while IFS= read -r line
do
  if [[ -n "$line" ]]; then
    full_path="$base_dir/$line"
    sudo rm -rf "$full_path"
  fi
done < "$lista_file"


sudo find /opt/4rji/bin/* -type f -exec sed -i 's|^#!/bin/bash|#!/run/current-system/sw/bin/bash|' {} +

sudo find /opt/4rji/bin/* -type f -exec sed -i 's|^#!/bin/zsh|#!/run/current-system/sw/bin/bash|' {} +

sudo find /opt/4rji/bin/* -type f -exec sed -i 's|^#!/usr/bin/python3|#!/etc/profiles/per-user/nala/bin/python3|' {} +


todou
