FROM debian:bookworm

RUN apt-get update && \
    apt-get install -y \
        firefox-esr \
        locales \
        libgtk-3-0 \
        libdbus-glib-1-2 \
        libx11-xcb1 \
        libasound2 \
        libpci3 \
        libegl1 \
        x11-utils && \
    sed -i '/es_ES.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["firefox-esr"]

